<hr>

# 🧫 DATA CLEANING 🧫

<style>
h1 {
    text-align: center;
    color: blue;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<hr>

<hr>

## 0️⃣ DATA EXPLORATION


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [1]:
import pandas as pd
from IPython.display import display

# Load online_shoppers_intention.csv into a df_main DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv")

# Display df DataFrame SHAPE
print("exploring Dataset:")
print(f"Main Dataset Shape: [{df.shape[0]}] ROWS and [{df.shape[1]}] COLUMNS\n")

# Display df DataFrame HEAD
display(df.head(10))

# Display data types & missing values of each column in df DataFrame
print("Data Types & Missing Values of Each Column:")
display(df.info())

exploring Dataset:
Main Dataset Shape: [10910] ROWS and [26] COLUMNS

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
5,5,HO81102,NaN,4745.181764,NaN,Basic,High School or Below,2/14/11,Employed,M,...,0.0,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,A
6,6,IW72280,California,5035.035257,No,Basic,Doctor,2/14/11,Employed,F,...,3.0,4,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medsize,NaN
7,7,IH64929,California,4956.247235,No,Basic,High School or Below,2/24/11,Employed,M,...,0.0,3,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medsize,NaN
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
9,9,QX31376,Oregon,17114.328150,No,Extended,Master,1/4/11,Employed,F,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,NaN

Data Types & Missing Values of Each Column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

None

In [4]:
# Display the list of column names in df
print("Column Names in df_main:")
display(df.columns.tolist())

# Loop through each column and print unique values
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"{col}")
    print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")

print(f"\nData types check:")
for col in df.columns:
    dtype = df[col].dtype
    unique_vals = df[col].nunique()
    print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")

Column Names in df_main:

['Unnamed: 0',
 'Customer',
 'State',
 'Customer Lifetime Value',
 'Response',
 'Coverage',
 'Education',
 'Effective To Date',
 'EmploymentStatus',
 'Gender',
 'Income',
 'Location Code',
 'Marital Status',
 'Monthly Premium Auto',
 'Months Since Last Claim',
 'Months Since Policy Inception',
 'Number of Open Complaints',
 'Number of Policies',
 'Policy Type',
 'Policy',
 'Renew Offer Type',
 'Sales Channel',
 'Total Claim Amount',
 'Vehicle Class',
 'Vehicle Size',
 'Vehicle Type']

Unnamed: 0
Unique values (10910): [    0     1     2 ... 10907 10908 10909]

Customer
Unique values (9134): ['DK49336' 'KX64629' 'LZ68649' ... 'KX53892' 'TL39050' 'WA60547']

State
Unique values (6): ['Arizona' 'California' 'Washington' 'Oregon' nan 'Nevada']

Customer Lifetime Value
Unique values (8041): [ 4809.21696   2228.525238 14947.9173   ...  5259.444853 23893.3041
 11971.97765 ]

Response
Unique values (3): ['No' 'Yes' nan]

Coverage
Unique values (3): ['Basic' 'Extended' 'Premium']

Education
Unique values (5): ['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']

Effective To Date
Unique values (59): ['2/18/11' '1/18/11' '2/10/11' '1/11/11' '1/17/11' '2/14/11' '2/24/11'
 '1/19/11' '1/4/11' '1/2/11' '2/7/11' '1/31/11' '1/26/11' '2/28/11'
 '1/16/11' '2/26/11' '2/23/11' '1/15/11' '2/2/11' '2/15/11' '1/24/11'
 '2/21/11' '2/22/11' '1/7/11' '1/28/11' '2/8/11' '2/12/11' '2/20/11'
 '1/5/11' '2/19/11' '1/3/11' '2/3/11' '1/22/11' '1/23/11' '2/5/11'
 '2/13/11' '1/25/11' '2/16/11' '2/1/11' '1/27/11' '1/12/11' '1/20/11'
 '2/6/11' '2/11/11' '1/21/11' '1/29/11' '1/9/11' '2/9/11' '2/27/11'
 '1/1/11' '2/17/11' '2/25/11' '1/13/11' '1/6/11' '2/4/11' '1/14/11'
 '1/10/11' '1/8/11' '1/30/11']

EmploymentStatus
Unique values (5): ['Employed' 'Unemployed' 'Medical Leave' 'Disabled' 'Retired']

Gender
Unique values (2): ['M' 'F']

Income
Unique values (5694): [48029     0 22139 ... 61146 39837 64195]

Location Code
Unique values (3): ['Suburban' 'Urban' 'Rural']

Marital Status
Unique values (3): ['Married' 'Single' 'Divorced']

Monthly Premium Auto
Unique values (202): [ 61  64 100  97 117  63 154  85 127  62  99  69 116 114  66  73  94 104
 189  74 121 110 111  72 115 159 101  65  82  71 126  68 199  96  67 125
 249 105  92  78  77  79 223 242  70 102 109 107 119 194 113 106 247  80
  86  81  83 122 253 196 132 139  84 130  93 103 112 222 118  88 182 283
  90 128  89 235 190  76  87 133 153 129  98 148 123  91 211 131 108 187
 214 181 173 252  95 124 137 145 188 143 198 138 245 195 186 170 136 161
 157 141 205 271 192 142 140 134 240 185 244 210 184 202 296 213 273 219
 135 169 155 225 266 215 197 256 212 158 180 166 168 183 162 191 179 150
 146 276 165 239 237 193 229 274 207 295 208 172 217 206 201 171 152 156
 174 238 167 151 144 163 287 209 290 220 228 232 178 177 275 176 281 149
 298 255 216 285 226 160 147 254 164 175 297 234 284 204 218 261 231 248
 286 230 268 203]

Months Since Last Claim
Unique values (37): [ 7.  3. 34. 10. nan  2.  8. 35. 33. 19. 13.  5. 24. 25.  6. 20. 26. 14.
  9. 29. 11.  1. 18. 16. 30. 12.  4. 22. 31. 21. 28. 17. 15. 32. 23. 27.
  0.]

Months Since Policy Inception
Unique values (100): [52 26 31  3 73 99 45 24  8 29 32 25 28 87 10 74  1 38 58 37  7 80 95 78
 63 27 97 39 11 59 46 62 13 54 51 22 82 91 44 43 76 48 84  6 92 12 61  4
 18 66 70 16 75 34 35 64  9 89  0 60 71 23 55 93  2 67 81 40 57 86 19 72
 69 33 47 42 17 49 21 83 94 30 15 50 53 77 41 90  5 79 56 98 20 88 65 14
 85 96 36 68]

Number of Open Complaints
Unique values (7): [ 0. nan  3.  1.  2.  4.  5.]

Number of Policies
Unique values (9): [9 1 2 7 4 3 6 8 5]

Policy Type
Unique values (3): ['Corporate Auto' 'Personal Auto' 'Special Auto']

Policy
Unique values (9): ['Corporate L3' 'Personal L3' 'Personal L2' 'Corporate L2' 'Personal L1'
 'Special L1' 'Corporate L1' 'Special L3' 'Special L2']

Renew Offer Type
Unique values (4): ['Offer3' 'Offer4' 'Offer2' 'Offer1']

Sales Channel
Unique values (4): ['Agent' 'Call Center' 'Branch' 'Web']

Total Claim Amount
Unique values (5106): [292.8      744.924331 480.       ... 273.018929 381.306996 618.288849]

Vehicle Class
Unique values (7): ['Four-Door Car' 'SUV' 'Two-Door Car' 'Sports Car' 'Luxury Car'
 'Luxury SUV' nan]

Vehicle Size
Unique values (4): ['Medsize' 'Small' 'Large' nan]

Vehicle Type
Unique values (2): [nan 'A']


Data types check:
  ➡️Unnamed: 0                int64      [10910] unique values
  ➡️Customer                  object     [9134] unique values
  ➡️State                     object     [5] unique values
  ➡️Customer Lifetime Value   float64    [8041] unique values
  ➡️Response                  object     [2] unique values
  ➡️Coverage                  object     [3] unique values
  ➡️Education                 object     [5] unique values
  ➡️Effective To Date         object     [59] unique values
  ➡️EmploymentStatus          object     [5] unique values
  ➡️Gender                    object     [2] unique values
  ➡️Income                    int64      [5694] unique values
  ➡️Location Code             object     [3] unique values
  ➡️Marital Status            object     [3] unique values
  ➡️Monthly Premium Auto      int64      [202] unique values
  ➡️Months Since Last Claim   float64    [36] unique values
  ➡️Months Since Policy Inception int64      [100] unique values
  ➡️Number of Open Complaints float64    [6] unique values
  ➡️Number of Policies        int64      [9] unique values
  ➡️Policy Type               object     [3] unique values
  ➡️Policy                    object     [9] unique values
  ➡️Renew Offer Type          object     [4] unique values
  ➡️Sales Channel             object     [4] unique values
  ➡️Total Claim Amount        float64    [5106] unique values
  ➡️Vehicle Class             object     [6] unique values
  ➡️Vehicle Size              object     [3] unique values
  ➡️Vehicle Type              object     [1] unique values

<hr>

## 1️⃣ STANDARDIZE COLUMN NAMES 


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [5]:
import pandas as pd

# Define the Renaming Dictionary
rename_columns = {
 'Customer': 'customer_id',
 'State': 'state',
 'Customer Lifetime Value': 'customer_lifetime_value',
 'Response': 'response',
 'Coverage': 'coverage',
 'Education': 'education',
 'Effective To Date': 'effective_to_date',
 'EmploymentStatus': 'employment_status',
 'Gender': 'gender',
 'Income': 'income',
 'Location Code': 'location_code',
 'Marital Status': 'marital_status',
 'Monthly Premium Auto': 'monthly_premium_auto',
 'Months Since Last Claim': 'months_since_last_claim',
 'Months Since Policy Inception': 'months_since_policy_inception',
 'Number of Open Complaints': 'number_open_complaints',
 'Number of Policies': 'number_of_policies',
 'Policy Type': 'policy_type',
 'Policy': 'policy',
 'Renew Offer Type': 'renew_offer_type',
 'Sales Channel': 'sales_channel',
 'Total Claim Amount': 'total_claim_amount',
 'Vehicle Class': 'vehicle_class',
 'Vehicle Size': 'vehicle_size',
 'Vehicle Type': 'vehicle_type'
}


# Rename columns using the rename Dictionary
df.rename(columns=rename_columns, inplace=True)

# Save updated dataset into a new CSV file
df.to_csv("combined_01_standard.csv", index=False)

# Display Standardized DataFrame
print("Standardized DataFrame:")
display(df.head())

# Display the list of the standardidized column names in df
print("Standardized Column Names in df:")
display(df.columns.tolist())
display(df.info())

Standardized DataFrame:

,Unnamed: 0,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,...,number_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

Standardized Column Names in df:

['Unnamed: 0',
 'customer_id',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employment_status',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   customer_id                    10910 non-null  object
 2   state                          10279 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10279 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employment_status              10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10277 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_open_complaints         10277 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10288 non-null  object
 24  vehicle_size                   10288 non-null  object
 25  vehicle_type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

None

<hr>

## 2️⃣ INVALID VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [6]:
import pandas as pd
# Load the standardized dataset into a new DataFrame
df = pd.read_csv("combined_01_standard.csv")

# 01 - gender ---------------------------------------------------------------------------
print("Before: 'gender' unique values:", df['gender'].unique())
# mapping gender values
gender_mapping = {
    "female": "F",
    "Femal": "F",    
    "Male": "M"
}
# replace values in gender
df['gender'] = df['gender'].replace(gender_mapping)
# Check GENDER unique values after mapping
print("After: 'gender' unique values:", df['gender'].unique())
print(*70*"-")

# 02 - state ---------------------------------------------------------------------------
print("Before: 'state' unique values:", df['state'].unique())
# mapping gender values
state_mapping = {
    "WA": "Washington",
    "AZ": "Arizona",    
    "Cali": "California"
}
# replace values in state
df['state'] = df['state'].replace(state_mapping)
# Check STATE unique values after mapping
print("After: 'state' unique values:", df['state'].unique())
print(*70*"-")

# 03 - education ---------------------------------------------------------------------------
print("Before: 'education' unique values:", df['education'].unique())
# replace Bachelors with Bachelor in education_level
df['education'] = df['education'].replace('Bachelors', 'Bachelor')
# Check education unique values after mapping
print("After: 'education' unique values:", df['education'].unique())
print(*70*"-")


# 05 - vehicle_class --------------------------------------------------------------------------
print("Before: 'vehicle_class' unique values:", df['vehicle_class'].unique())
# mapping vehicle_class values
vehicle_mapping = {
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
}
# replace values in education_level
df['vehicle_class'] = df['vehicle_class'].replace(vehicle_mapping)
# Check unique values after mapping
print("After: 'vehicle_class' unique values:", df['vehicle_class'].unique())
print(*70*"-")



# Display the dataset after dealing with invalid values ----------------------------------------------------------------------
print("Dataset after dealing with invalid values:")
display(df.head())

# Save step 02 deal with invalid values dataset into a new CSV file ------------------------------
df.to_csv("combined_02_invalid-values.csv", index=False)

Before: 'gender' unique values: ['M' 'F']
After: 'gender' unique values: ['M' 'F']
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Before: 'state' unique values: ['Arizona' 'California' 'Washington' 'Oregon' nan 'Nevada']
After: 'state' unique values: ['Arizona' 'California' 'Washington' 'Oregon' nan 'Nevada']
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Before: 'education' unique values: ['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']
After: 'education' unique values: ['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Before: 'vehicle_class' unique values: ['Four-Door Car' 'SUV' 'Two-Door Car' 'Sports Car' 'Luxury Car'
 'Luxury SUV' nan]
After: 'vehicle_class' unique values: ['Four-Door Car' 'SUV' 'Two-Door Car' 'Luxury' nan]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dataset after dealing with invalid values:

,Unnamed: 0,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,...,number_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

<hr>

## 3️⃣ DATA TYPES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [7]:
import pandas as pd

# Load the step 02 dataset into a new DataFrame
df = pd.read_csv("combined_02_invalid-values.csv")

# check data types before data formatting
print("Data types before data formatting:")
df.info()

Data types before data formatting:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   customer_id                    10910 non-null  object
 2   state                          10279 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10279 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employment_status              10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10277 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_open_complaints         10277 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10288 non-null  object
 24  vehicle_size                   10288 non-null  object
 25  vehicle_type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [8]:
# convert number_open_complaints to integer type
df['number_open_complaints'] = pd.to_numeric(df['number_open_complaints'], errors='coerce').astype('Int64')

# check data types after data formatting
print("Data types after data formatting:")
df.info()
print("*" * 70)

# display the dataset after data formatting ----------------------------------------------------------------------
print("Dataset after data formatting:")
print("Dataset shape:", df.shape)
display(df.head())

# save step 3 data formatting dataset into a new CSV file ------------------------------
df.to_csv("combined_03_data-formatting.csv", index=False)

Data types after data formatting:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   customer_id                    10910 non-null  object
 2   state                          10279 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10279 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employment_status              10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10277 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_open_complaints         10277 non-null  Int64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10288 non-null  object
 24  vehicle_size                   10288 non-null  object
 25  vehicle_type                   5428 non-null   object
dtypes: Int64(1), float64(3), int64(5), object(17)
memory usage: 2.2+ MB
**********************************************************************
Dataset after data formatting:
Dataset shape: (10910, 26)

,Unnamed: 0,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,...,number_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,<NA>,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

<hr>

## 4️⃣ NULL VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [9]:
import pandas as pd
# read csv
df = pd.read_csv("combined_03_data-formatting.csv")

# Check for null values
null_counts = df.isnull().sum()
print(f"Total null count in the Dataframe = {null_counts.sum()}\n")

# Identify how many null values each column has. 
print("Columns with null values:")
display(null_counts[null_counts > 0])

print("-" * 70)

# show null values in each column
print("Null values in each column:")
# Loop through each column and print the number of nulls in each column
for col in df.columns:
    null_count = df[col].isnull().sum()
    print(f"Column '{col}'➡️[{null_count}] null values")

Total null count in the Dataframe = 9254

Columns with null values:

state                       631
response                    631
months_since_last_claim     633
number_open_complaints      633
vehicle_class               622
vehicle_size                622
vehicle_type               5482
dtype: int64

----------------------------------------------------------------------
Null values in each column:
Column 'Unnamed: 0'➡️[0] null values
Column 'customer_id'➡️[0] null values
Column 'state'➡️[631] null values
Column 'customer_lifetime_value'➡️[0] null values
Column 'response'➡️[631] null values
Column 'coverage'➡️[0] null values
Column 'education'➡️[0] null values
Column 'effective_to_date'➡️[0] null values
Column 'employment_status'➡️[0] null values
Column 'gender'➡️[0] null values
Column 'income'➡️[0] null values
Column 'location_code'➡️[0] null values
Column 'marital_status'➡️[0] null values
Column 'monthly_premium_auto'➡️[0] null values
Column 'months_since_last_claim'➡️[633] null values
Column 'months_since_policy_inception'➡️[0] null values
Column 'number_open_complaints'➡️[633] null values
Column 'number_of_policies'➡️[0] null values
Column 'policy_type'➡️[0] null values
Column 'policy'➡️[0] null values
Column 'renew_offer_type'➡️[0] null values
Column 'sales_channel'➡️[0] null values
Column 'total_claim_amount'➡️[0] null values
Column 'vehicle_class'➡️[622] null values
Column 'vehicle_size'➡️[622] null values
Column 'vehicle_type'➡️[5482] null values

In [10]:
# show unique values of each column
print("\nUnique values in each column:")
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"{col}")
    print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")

Unique values in each column:
Unnamed: 0
Unique values (10910): [    0     1     2 ... 10907 10908 10909]

customer_id
Unique values (9134): ['DK49336' 'KX64629' 'LZ68649' ... 'KX53892' 'TL39050' 'WA60547']

state
Unique values (6): ['Arizona' 'California' 'Washington' 'Oregon' nan 'Nevada']

customer_lifetime_value
Unique values (8041): [ 4809.21696   2228.525238 14947.9173   ...  5259.444853 23893.3041
 11971.97765 ]

response
Unique values (3): ['No' 'Yes' nan]

coverage
Unique values (3): ['Basic' 'Extended' 'Premium']

education
Unique values (5): ['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']

effective_to_date
Unique values (59): ['2/18/11' '1/18/11' '2/10/11' '1/11/11' '1/17/11' '2/14/11' '2/24/11'
 '1/19/11' '1/4/11' '1/2/11' '2/7/11' '1/31/11' '1/26/11' '2/28/11'
 '1/16/11' '2/26/11' '2/23/11' '1/15/11' '2/2/11' '2/15/11' '1/24/11'
 '2/21/11' '2/22/11' '1/7/11' '1/28/11' '2/8/11' '2/12/11' '2/20/11'
 '1/5/11' '2/19/11' '1/3/11' '2/3/11' '1/22/11' '1/23/11' '2/5/11'
 '2/13/11' '1/25/11' '2/16/11' '2/1/11' '1/27/11' '1/12/11' '1/20/11'
 '2/6/11' '2/11/11' '1/21/11' '1/29/11' '1/9/11' '2/9/11' '2/27/11'
 '1/1/11' '2/17/11' '2/25/11' '1/13/11' '1/6/11' '2/4/11' '1/14/11'
 '1/10/11' '1/8/11' '1/30/11']

employment_status
Unique values (5): ['Employed' 'Unemployed' 'Medical Leave' 'Disabled' 'Retired']

gender
Unique values (2): ['M' 'F']

income
Unique values (5694): [48029     0 22139 ... 61146 39837 64195]

location_code
Unique values (3): ['Suburban' 'Urban' 'Rural']

marital_status
Unique values (3): ['Married' 'Single' 'Divorced']

monthly_premium_auto
Unique values (202): [ 61  64 100  97 117  63 154  85 127  62  99  69 116 114  66  73  94 104
 189  74 121 110 111  72 115 159 101  65  82  71 126  68 199  96  67 125
 249 105  92  78  77  79 223 242  70 102 109 107 119 194 113 106 247  80
  86  81  83 122 253 196 132 139  84 130  93 103 112 222 118  88 182 283
  90 128  89 235 190  76  87 133 153 129  98 148 123  91 211 131 108 187
 214 181 173 252  95 124 137 145 188 143 198 138 245 195 186 170 136 161
 157 141 205 271 192 142 140 134 240 185 244 210 184 202 296 213 273 219
 135 169 155 225 266 215 197 256 212 158 180 166 168 183 162 191 179 150
 146 276 165 239 237 193 229 274 207 295 208 172 217 206 201 171 152 156
 174 238 167 151 144 163 287 209 290 220 228 232 178 177 275 176 281 149
 298 255 216 285 226 160 147 254 164 175 297 234 284 204 218 261 231 248
 286 230 268 203]

months_since_last_claim
Unique values (37): [ 7.  3. 34. 10. nan  2.  8. 35. 33. 19. 13.  5. 24. 25.  6. 20. 26. 14.
  9. 29. 11.  1. 18. 16. 30. 12.  4. 22. 31. 21. 28. 17. 15. 32. 23. 27.
  0.]

months_since_policy_inception
Unique values (100): [52 26 31  3 73 99 45 24  8 29 32 25 28 87 10 74  1 38 58 37  7 80 95 78
 63 27 97 39 11 59 46 62 13 54 51 22 82 91 44 43 76 48 84  6 92 12 61  4
 18 66 70 16 75 34 35 64  9 89  0 60 71 23 55 93  2 67 81 40 57 86 19 72
 69 33 47 42 17 49 21 83 94 30 15 50 53 77 41 90  5 79 56 98 20 88 65 14
 85 96 36 68]

number_open_complaints
Unique values (7): [ 0. nan  3.  1.  2.  4.  5.]

number_of_policies
Unique values (9): [9 1 2 7 4 3 6 8 5]

policy_type
Unique values (3): ['Corporate Auto' 'Personal Auto' 'Special Auto']

policy
Unique values (9): ['Corporate L3' 'Personal L3' 'Personal L2' 'Corporate L2' 'Personal L1'
 'Special L1' 'Corporate L1' 'Special L3' 'Special L2']

renew_offer_type
Unique values (4): ['Offer3' 'Offer4' 'Offer2' 'Offer1']

sales_channel
Unique values (4): ['Agent' 'Call Center' 'Branch' 'Web']

total_claim_amount
Unique values (5106): [292.8      744.924331 480.       ... 273.018929 381.306996 618.288849]

vehicle_class
Unique values (5): ['Four-Door Car' 'SUV' 'Two-Door Car' 'Luxury' nan]

vehicle_size
Unique values (4): ['Medsize' 'Small' 'Large' nan]

vehicle_type
Unique values (2): [nan 'A']

In [11]:
# null values in the dataset before dealing with null values
null_counts_before = df.isnull().sum()


# null values in education column BEFORE
print("BEFORE, null values in education column:", df['education'].isnull().sum())
# fill null values in education column with 'Not Specified'
df['education'] = df['education'].fillna('Not Specified')
# null values in education column AFTER
print("AFTER, null values in education column:", df['education'].isnull().sum())
print("-" * 70)

# null values in customer_lifetime_value BEFORE
print("BEFORE, null values in customer_lifetime_value column:", df['customer_lifetime_value'].isnull().sum())
# fill null values in customer_lifetime_value column with median value of the column
df['customer_lifetime_value'] = df['customer_lifetime_value'].fillna(df['customer_lifetime_value'].median())
# null values in customer_lifetime_value column AFTER
print("AFTER, null values in customer_lifetime_value column:", df['customer_lifetime_value'].isnull().sum()) 
print("-" * 70)

# null values in gender column
print("null values in gender column:", df['gender'].isnull().sum())
# fill null values in gender column with 'U' for unknown
df['gender'] = df['gender'].fillna('U')
# null values in gender column AFTER
print("AFTER, null values in gender column:", df['gender'].isnull().sum())
print("-" * 70)

# null values in state column
print("null values in state column:", df['state'].isnull().sum())
# fill null values in state column with 'Not Specified'
df['state'] = df['state'].fillna('Not Specified')
# null values in state column AFTER
print("AFTER, null values in state column:", df['state'].isnull().sum())
print("-" * 70)

# null values in number_open_complaints column
print("null values in number_open_complaints column:", df['number_open_complaints'].isnull().sum())
# fill number_open_complaints null values with 0
df['number_open_complaints'] = df['number_open_complaints'].fillna(0)
# null values in number_open_complaints column AFTER
print("AFTER, null values in number_open_complaints column:", df['number_open_complaints'].isnull().sum())
print("-" * 70)

# null values in vehicle_class column
print("null values in vehicle_class column:", df['vehicle_class'].isnull().sum())
# fill null values in vehicle_class column with 'Not Specified'
df['vehicle_class'] = df['vehicle_class'].fillna('Not Specified')
# null values in vehicle_class column AFTER
print("AFTER, null values in vehicle_class column:", df['vehicle_class'].isnull().sum())
print("-" * 70)

# null values in customer_id column
print("null values in customer_id column:", df['customer_id'].isnull().sum())
# drop rows with null values in customer_id column
df = df.dropna(subset=['customer_id'])
# null values in customer_id column AFTER
print("AFTER, null values in customer_id column:", df['customer_id'].isnull().sum())
print("-" * 70)

# after dealing with null values in the dataset, check for null values again
null_counts_after = df.isnull().sum()
print("Null values in each column after dealing with null values:")
display(null_counts_after)

# save in a new csv file the dataset after dealing with null values
df.to_csv("combined_04_no-nulls.csv", index=False)

# display the dataset after dealing with null values ----------------------------------------------------------------------
print("Dataset after dealing with null values:")
print("Dataset shape:", df.shape)
display(df.head())

BEFORE, null values in education column: 0
AFTER, null values in education column: 0
----------------------------------------------------------------------
BEFORE, null values in customer_lifetime_value column: 0
AFTER, null values in customer_lifetime_value column: 0
----------------------------------------------------------------------
null values in gender column: 0
AFTER, null values in gender column: 0
----------------------------------------------------------------------
null values in state column: 631
AFTER, null values in state column: 0
----------------------------------------------------------------------
null values in number_open_complaints column: 633
AFTER, null values in number_open_complaints column: 0
----------------------------------------------------------------------
null values in vehicle_class column: 622
AFTER, null values in vehicle_class column: 0
----------------------------------------------------------------------
null values in customer_id column: 0
AFTER, null values in customer_id column: 0
----------------------------------------------------------------------
Null values in each column after dealing with null values:

Unnamed: 0                          0
customer_id                         0
state                               0
customer_lifetime_value             0
response                          631
coverage                            0
education                           0
effective_to_date                   0
employment_status                   0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim           633
months_since_policy_inception       0
number_open_complaints              0
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                       0
vehicle_size                      622
vehicle_type                     5482
dtype: int64

Dataset after dealing with null values:
Dataset shape: (10910, 26)

,Unnamed: 0,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,...,number_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,0.0,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   customer_id                    10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10279 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employment_status              10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10277 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_open_complaints         10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10288 non-null  object
 25  vehicle_type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

<hr>

## 5️⃣ DUPLICATE VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [13]:
import pandas as pd

# read csv into a new DataFrame
df = pd.read_csv("combined_04_no-nulls.csv")

# Check for duplicate rows in the DataFrame
duplicate_rows = df[df.duplicated()]

# Shape of the dataset before dropping duplicate rows
print("Dataset shape before dropping duplicates:", df.shape)

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicate_rows.shape[0]}")

# Display the duplicate rows
if duplicate_rows.empty:
    print("No duplicate rows found.")
else:
    print("\nDuplicate rows:")
    display(duplicate_rows)

print(*70*"-")

# drop duplicate rows, keeping the first occurrence
print("Dropping duplicate rows, keeping the first occurrence...")
df.drop_duplicates(keep='first', inplace=True)
duplicate_rows = df[df.duplicated()]

# Display the duplicate rows
if duplicate_rows.empty:
    print("No duplicate rows found.")
else:
    print("\nDuplicate rows:")
    display(duplicate_rows)
    
# save the dataset after dropping duplicate rows into a new CSV file
df.to_csv("combined_05_no-duplicates.csv", index=False)

Dataset shape before dropping duplicates: (10910, 26)
Number of duplicate rows: 0
No duplicate rows found.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dropping duplicate rows, keeping the first occurrence...
No duplicate rows found.

In [14]:
import pandas as pd
# read csv into a new DataFrame
df = pd.read_csv("combined_05_no-duplicates.csv")

# display the dataset ----------------------------------------------------------------------
print("Clean Dataset:")
print("Clean Dataset shape:", df.shape)
display(df.head(20))

# save the clean dataset into a new CSV file
df.to_csv("combined_06_clean.csv", index=False)

Clean Dataset:
Clean Dataset shape: (10910, 26)

,Unnamed: 0,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,...,number_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,0.0,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
5,5,HO81102,Not Specified,4745.181764,NaN,Basic,High School or Below,2/14/11,Employed,M,...,0.0,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,A
6,6,IW72280,California,5035.035257,No,Basic,Doctor,2/14/11,Employed,F,...,3.0,4,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medsize,NaN
7,7,IH64929,California,4956.247235,No,Basic,High School or Below,2/24/11,Employed,M,...,0.0,3,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medsize,NaN
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Luxury,Medsize,NaN
9,9,QX31376,Oregon,17114.328150,No,Extended,Master,1/4/11,Employed,F,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,NaN
10,10,HG93801,Arizona,5154.764074,No,Extended,High School or Below,1/2/11,Employed,M,...,0.0,1,Corporate Auto,Corporate L3,Offer2,Branch,442.521087,SUV,Large,A
11,11,GE63585,Not Specified,2420.711888,NaN,Basic,Bachelor,2/7/11,Employed,M,...,0.0,1,Corporate Auto,Corporate L3,Offer1,Call Center,199.551735,Two-Door Car,Medsize,NaN
12,12,EO51920,Oregon,19955.257130,No,Extended,High School or Below,1/31/11,Employed,F,...,0.0,2,Corporate Auto,Corporate L3,Offer1,Agent,64.669515,Four-Door Car,Medsize,NaN
13,13,KR82385,California,5454.587929,No,Basic,Master,1/26/11,Employed,M,...,0.0,4,Personal Auto,Personal L3,Offer4,Call Center,331.200000,Two-Door Car,Medsize,A
14,14,TL59568,Arizona,12836.009510,No,Premium,High School or Below,2/28/11,Unemployed,M,...,0.0,2,Personal Auto,Personal L2,Offer3,Agent,835.200000,Two-Door Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
16,16,FH51383,California,5326.677654,No,Basic,High School or Below,2/7/11,Employed,F,...,0.0,6,Personal Auto,Personal L3,Offer4,Call Center,300.528579,Two-Door Car,Large,A
17,17,TR26615,Oregon,2497.531509,No,Basic,High School or Below,1/17/11,Unemployed,M,...,0.0,1,Corporate Auto,Corporate L2,Offer2,Branch,272.381465,Two-Door Car,Medsize,A
18,18,ZC97968,California,2736.352663,No,Basic,College,2/14/11,Disabled,M,...,0.0,1,Personal Auto,Personal L3,Offer1,Agent,350.400000,Two-Door Car,Medsize,A
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A

---
## Solved Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called `marketing_customer_analysis.csv`, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as `customer demographics`, `policy details`, `vehicle information`, and the `customer's response to the last marketing campaign`. 

Our **goal** is to **explore and analyze this data by performing data cleaning, formatting, and structuring**.

<hr>

## 0️⃣ DATA EXPLORATION


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [15]:
import pandas as pd

# read the three csv files into seperate dataframes
df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')


# Display df DataFrame
print("Exploring the Marketing Customer Dataset:")
# Display df DataFrame SHAPE
print(f"Main Dataset Shape: [{df.shape[0]}] ROWS and [{df.shape[1]}] COLUMNS\n")
# Display df DataFrame HEAD
display(df.head(10))

# Display data types & missing values of each column in df DataFrame
print("Data Types & Missing Values of Each Column:")
display(df.info())

# Check for null values
print(f"Total null count in the Dataframe = {null_counts.sum()}\n")
print("There are 0 null values in the dataset!")

Exploring the Marketing Customer Dataset:
Main Dataset Shape: [10910] ROWS and [27] COLUMNS

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
5,5,HO81102,California,4745.181764,No,Basic,High School or Below,2011-02-14,Employed,M,...,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,A,2
6,6,IW72280,California,5035.035257,No,Basic,Doctor,2011-02-14,Employed,F,...,4,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medsize,A,2
7,7,IH64929,California,4956.247235,No,Basic,High School or Below,2011-02-24,Employed,M,...,3,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medsize,A,2
8,8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,A,1
9,9,QX31376,Oregon,17114.328150,No,Extended,Master,2011-01-04,Employed,F,...,2,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,A,1

Data Types & Missing Values of Each Column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

None

Total null count in the Dataframe = 9254

There are 0 null values in the dataset!

<hr>

## 1️⃣ STANDARDIZE COLUMN NAMES 


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [16]:
import pandas as pd
from IPython.display import display

# drop the 'Unnamed: 0' column
df.drop(columns=['unnamed:_0'], inplace=True)

# save the dataset after dropping the 'unnamed:_0' column into a new CSV file
df.to_csv("marketing_customer_analysis_00_drop-column.csv", index=False)

# read csv into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_00_drop-column.csv")

# Display df DataFrame
print("Exploring the Marketing Customer Dataset:")

# Display df DataFrame SHAPE
print(f"Main Dataset Shape: [{df.shape[0]}] ROWS and [{df.shape[1]}] COLUMNS\n")

# Display df DataFrame HEAD
display(df.head(10))

# Display data types & missing values of each column in df DataFrame
print("Data Types & Missing Values of Each Column:")
display(df.info())

Exploring the Marketing Customer Dataset:
Main Dataset Shape: [10910] ROWS and [26] COLUMNS

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
5,HO81102,California,4745.181764,No,Basic,High School or Below,2011-02-14,Employed,M,50549,...,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,A,2
6,IW72280,California,5035.035257,No,Basic,Doctor,2011-02-14,Employed,F,37405,...,4,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medsize,A,2
7,IH64929,California,4956.247235,No,Basic,High School or Below,2011-02-24,Employed,M,87197,...,3,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medsize,A,2
8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,66839,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,A,1
9,QX31376,Oregon,17114.328150,No,Extended,Master,2011-01-04,Employed,F,70961,...,2,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,A,1

Data Types & Missing Values of Each Column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer                       10910 non-null  object
 1   state                          10910 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10910 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  object
 7   employmentstatus               10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10910 non-null  float64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10910 non-null  float64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10910 non-null  object
 23  vehicle_size                   10910 non-null  object
 24  vehicle_type                   10910 non-null  object
 25  month                          10910 non-null  int64
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

None

In [17]:
# check unique values of each column -----------------------------------------------------------------------
# Display the list of column names in df
print("Column Names in df_main:")
display(df.columns.tolist())

# Loop through each column and print unique values
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"Column: {col}")
    print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")

print(f"\nData types check:")
for col in df.columns:
    dtype = df[col].dtype
    unique_vals = df[col].nunique()
    print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")

# save the dataset after exploring it into a new CSV file
df.to_csv("marketing_customer_analysis_00_explore.csv", index=False)

Column Names in df_main:

['customer',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employmentstatus',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type',
 'month']

Column: customer
Unique values (9134): ['DK49336' 'KX64629' 'LZ68649' ... 'KX53892' 'TL39050' 'WA60547']

Column: state
Unique values (5): ['Arizona' 'California' 'Washington' 'Oregon' 'Nevada']

Column: customer_lifetime_value
Unique values (8041): [ 4809.21696   2228.525238 14947.9173   ...  5259.444853 23893.3041
 11971.97765 ]

Column: response
Unique values (2): ['No' 'Yes']

Column: coverage
Unique values (3): ['Basic' 'Extended' 'Premium']

Column: education
Unique values (5): ['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']

Column: effective_to_date
Unique values (59): ['2011-02-18' '2011-01-18' '2011-02-10' '2011-01-11' '2011-01-17'
 '2011-02-14' '2011-02-24' '2011-01-19' '2011-01-04' '2011-01-02'
 '2011-02-07' '2011-01-31' '2011-01-26' '2011-02-28' '2011-01-16'
 '2011-02-26' '2011-02-23' '2011-01-15' '2011-02-02' '2011-02-15'
 '2011-01-24' '2011-02-21' '2011-02-22' '2011-01-07' '2011-01-28'
 '2011-02-08' '2011-02-12' '2011-02-20' '2011-01-05' '2011-02-19'
 '2011-01-03' '2011-02-03' '2011-01-22' '2011-01-23' '2011-02-05'
 '2011-02-13' '2011-01-25' '2011-02-16' '2011-02-01' '2011-01-27'
 '2011-01-12' '2011-01-20' '2011-02-06' '2011-02-11' '2011-01-21'
 '2011-01-29' '2011-01-09' '2011-02-09' '2011-02-27' '2011-01-01'
 '2011-02-17' '2011-02-25' '2011-01-13' '2011-01-06' '2011-02-04'
 '2011-01-14' '2011-01-10' '2011-01-08' '2011-01-30']

Column: employmentstatus
Unique values (5): ['Employed' 'Unemployed' 'Medical Leave' 'Disabled' 'Retired']

Column: gender
Unique values (2): ['M' 'F']

Column: income
Unique values (5694): [48029     0 22139 ... 61146 39837 64195]

Column: location_code
Unique values (3): ['Suburban' 'Urban' 'Rural']

Column: marital_status
Unique values (3): ['Married' 'Single' 'Divorced']

Column: monthly_premium_auto
Unique values (202): [ 61  64 100  97 117  63 154  85 127  62  99  69 116 114  66  73  94 104
 189  74 121 110 111  72 115 159 101  65  82  71 126  68 199  96  67 125
 249 105  92  78  77  79 223 242  70 102 109 107 119 194 113 106 247  80
  86  81  83 122 253 196 132 139  84 130  93 103 112 222 118  88 182 283
  90 128  89 235 190  76  87 133 153 129  98 148 123  91 211 131 108 187
 214 181 173 252  95 124 137 145 188 143 198 138 245 195 186 170 136 161
 157 141 205 271 192 142 140 134 240 185 244 210 184 202 296 213 273 219
 135 169 155 225 266 215 197 256 212 158 180 166 168 183 162 191 179 150
 146 276 165 239 237 193 229 274 207 295 208 172 217 206 201 171 152 156
 174 238 167 151 144 163 287 209 290 220 228 232 178 177 275 176 281 149
 298 255 216 285 226 160 147 254 164 175 297 234 284 204 218 261 231 248
 286 230 268 203]

Column: months_since_last_claim
Unique values (37): [ 7.          3.         34.         10.         15.14907074  2.
  8.         35.         33.         19.         13.          5.
 24.         25.          6.         20.         26.         14.
  9.         29.         11.          1.         18.         16.
 30.         12.          4.         22.         31.         21.
 28.         17.         15.         32.         23.         27.
  0.        ]

Column: months_since_policy_inception
Unique values (100): [52 26 31  3 73 99 45 24  8 29 32 25 28 87 10 74  1 38 58 37  7 80 95 78
 63 27 97 39 11 59 46 62 13 54 51 22 82 91 44 43 76 48 84  6 92 12 61  4
 18 66 70 16 75 34 35 64  9 89  0 60 71 23 55 93  2 67 81 40 57 86 19 72
 69 33 47 42 17 49 21 83 94 30 15 50 53 77 41 90  5 79 56 98 20 88 65 14
 85 96 36 68]

Column: number_of_open_complaints
Unique values (7): [0.         0.38425611 3.         1.         2.         4.
 5.        ]

Column: number_of_policies
Unique values (9): [9 1 2 7 4 3 6 8 5]

Column: policy_type
Unique values (3): ['Corporate Auto' 'Personal Auto' 'Special Auto']

Column: policy
Unique values (9): ['Corporate L3' 'Personal L3' 'Personal L2' 'Corporate L2' 'Personal L1'
 'Special L1' 'Corporate L1' 'Special L3' 'Special L2']

Column: renew_offer_type
Unique values (4): ['Offer3' 'Offer4' 'Offer2' 'Offer1']

Column: sales_channel
Unique values (4): ['Agent' 'Call Center' 'Branch' 'Web']

Column: total_claim_amount
Unique values (5106): [292.8      744.924331 480.       ... 273.018929 381.306996 618.288849]

Column: vehicle_class
Unique values (6): ['Four-Door Car' 'SUV' 'Two-Door Car' 'Sports Car' 'Luxury Car'
 'Luxury SUV']

Column: vehicle_size
Unique values (3): ['Medsize' 'Small' 'Large']

Column: vehicle_type
Unique values (1): ['A']

Column: month
Unique values (2): [2 1]


Data types check:
  ➡️customer                  object     [9134] unique values
  ➡️state                     object     [5] unique values
  ➡️customer_lifetime_value   float64    [8041] unique values
  ➡️response                  object     [2] unique values
  ➡️coverage                  object     [3] unique values
  ➡️education                 object     [5] unique values
  ➡️effective_to_date         object     [59] unique values
  ➡️employmentstatus          object     [5] unique values
  ➡️gender                    object     [2] unique values
  ➡️income                    int64      [5694] unique values
  ➡️location_code             object     [3] unique values
  ➡️marital_status            object     [3] unique values
  ➡️monthly_premium_auto      int64      [202] unique values
  ➡️months_since_last_claim   float64    [37] unique values
  ➡️months_since_policy_inception int64      [100] unique values
  ➡️number_of_open_complaints float64    [7] unique values
  ➡️number_of_policies        int64      [9] unique values
  ➡️policy_type               object     [3] unique values
  ➡️policy                    object     [9] unique values
  ➡️renew_offer_type          object     [4] unique values
  ➡️sales_channel             object     [4] unique values
  ➡️total_claim_amount        float64    [5106] unique values
  ➡️vehicle_class             object     [6] unique values
  ➡️vehicle_size              object     [3] unique values
  ➡️vehicle_type              object     [1] unique values
  ➡️month                     int64      [2] unique values

In [18]:
# 01 - standardize column names =====================================================================================================

import pandas as pd
# read csv into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_00_explore.csv")

# rename column employmentstatus to employment_status
df.rename(columns={'employmentstatus': 'employment_status'}, inplace=True)

# rename column customer to customer_id
df.rename(columns={'customer': 'customer_id'}, inplace=True)

# save to csv after standardizing column names
df.to_csv("marketing_customer_analysis_01_standardize.csv", index=False)

<hr>

## 2️⃣ INVALID VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [19]:
# 02 - deal with invalid values in the dataset ======================================================================================

import pandas as pd
# read csv into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_01_standardize.csv")

# number_of_open_complaints --------------------------------------------------------------------------
print("Before: 'number_of_open_complaints' unique values:", df['number_of_open_complaints'].unique())

# round numbers to the nearest integer in number_of_open_complaints column
df['number_of_open_complaints'] = df['number_of_open_complaints'].round().astype('Int64')

# replace 0.38425611  to 0 in number_of_open_complaints column
df['number_of_open_complaints'] = df['number_of_open_complaints'].replace(0.38425611, 0)

# Check unique values after formatting
print("After: 'number_of_open_complaints' unique values:", df['number_of_open_complaints'].unique())
print(*70*"-")


# vehicle_class --------------------------------------------------------------------------
print("Before: 'vehicle_class' unique values:", df['vehicle_class'].unique())
# mapping vehicle_class values
vehicle_mapping = {
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
}
# replace values in vehicle_class
df['vehicle_class'] = df['vehicle_class'].replace(vehicle_mapping)
# Check unique values after mapping
print("After: 'vehicle_class' unique values:", df['vehicle_class'].unique())
print(*70*"-")


# vehicle_size --------------------------------------------------------------------------
print("Before: 'vehicle_size' unique values:", df['vehicle_size'].unique())
# replace Medsize to Medium in vehicle_size
df['vehicle_size'] = df['vehicle_size'].replace('Medsize', 'Medium')
# Check unique values after mapping
print("After: 'vehicle_size' unique values:", df['vehicle_size'].unique())
print(*70*"-")


# month ---------------------------------------------------------------------------
print("Before: 'month' unique values:", df['month'].unique())
# replace 1 to Jan and 2 to Feb in month column
month_mapping = {
    1: 'Jan',
    2: 'Feb'
}
df['month'] = df['month'].replace(month_mapping)
# Check unique values after mapping
print("After: 'month' unique values:", df['month'].unique())
print(*70*"-")


# display the dataset after dealing with invalid values ----------------------------------------------------------------------
print("Dataset after dealing with invalid values:")
print("Dataset shape:", df.shape)
display(df.head())

# check unique values of each column -----------------------------------------------------------------------
# Display the list of column names in df
print("Column Names in df_main:")
display(df.columns.tolist())

# Loop through each column and print unique values
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"Column: {col}")
    print(f"Unique values ({len(unique_vals)}): {unique_vals}\n")

print(f"\nData types check:")
for col in df.columns:
    dtype = df[col].dtype
    unique_vals = df[col].nunique()
    print(f"  ➡️{col:<25} {str(dtype):<10} [{unique_vals}] unique values")

print(*70*"-")

df.info()
# save step 02 deal with invalid values dataset into a new CSV file ------------------------------
df.to_csv("marketing_customer_analysis_02_invalid-values.csv", index=False)

Before: 'number_of_open_complaints' unique values: [0.         0.38425611 3.         1.         2.         4.
 5.        ]
After: 'number_of_open_complaints' unique values: <IntegerArray>
[0, 3, 1, 2, 4, 5]
Length: 6, dtype: Int64
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Before: 'vehicle_class' unique values: ['Four-Door Car' 'SUV' 'Two-Door Car' 'Sports Car' 'Luxury Car'
 'Luxury SUV']
After: 'vehicle_class' unique values: ['Four-Door Car' 'SUV' 'Two-Door Car' 'Luxury']
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Before: 'vehicle_size' unique values: ['Medsize' 'Small' 'Large']
After: 'vehicle_size' unique values: ['Medium' 'Small' 'Large']
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Before: 'month' unique values: [2 1]
After: 'month' unique values: ['Feb' 'Jan']
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dataset after dealing with invalid values:
Dataset shape: (10910, 26)

,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medium,A,Feb
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medium,A,Jan
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medium,A,Feb
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medium,A,Jan
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medium,A,Jan

Column Names in df_main:

['customer_id',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employment_status',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type',
 'month']

Column: customer_id
Unique values (9134): ['DK49336' 'KX64629' 'LZ68649' ... 'KX53892' 'TL39050' 'WA60547']

Column: state
Unique values (5): ['Arizona' 'California' 'Washington' 'Oregon' 'Nevada']

Column: customer_lifetime_value
Unique values (8041): [ 4809.21696   2228.525238 14947.9173   ...  5259.444853 23893.3041
 11971.97765 ]

Column: response
Unique values (2): ['No' 'Yes']

Column: coverage
Unique values (3): ['Basic' 'Extended' 'Premium']

Column: education
Unique values (5): ['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']

Column: effective_to_date
Unique values (59): ['2011-02-18' '2011-01-18' '2011-02-10' '2011-01-11' '2011-01-17'
 '2011-02-14' '2011-02-24' '2011-01-19' '2011-01-04' '2011-01-02'
 '2011-02-07' '2011-01-31' '2011-01-26' '2011-02-28' '2011-01-16'
 '2011-02-26' '2011-02-23' '2011-01-15' '2011-02-02' '2011-02-15'
 '2011-01-24' '2011-02-21' '2011-02-22' '2011-01-07' '2011-01-28'
 '2011-02-08' '2011-02-12' '2011-02-20' '2011-01-05' '2011-02-19'
 '2011-01-03' '2011-02-03' '2011-01-22' '2011-01-23' '2011-02-05'
 '2011-02-13' '2011-01-25' '2011-02-16' '2011-02-01' '2011-01-27'
 '2011-01-12' '2011-01-20' '2011-02-06' '2011-02-11' '2011-01-21'
 '2011-01-29' '2011-01-09' '2011-02-09' '2011-02-27' '2011-01-01'
 '2011-02-17' '2011-02-25' '2011-01-13' '2011-01-06' '2011-02-04'
 '2011-01-14' '2011-01-10' '2011-01-08' '2011-01-30']

Column: employment_status
Unique values (5): ['Employed' 'Unemployed' 'Medical Leave' 'Disabled' 'Retired']

Column: gender
Unique values (2): ['M' 'F']

Column: income
Unique values (5694): [48029     0 22139 ... 61146 39837 64195]

Column: location_code
Unique values (3): ['Suburban' 'Urban' 'Rural']

Column: marital_status
Unique values (3): ['Married' 'Single' 'Divorced']

Column: monthly_premium_auto
Unique values (202): [ 61  64 100  97 117  63 154  85 127  62  99  69 116 114  66  73  94 104
 189  74 121 110 111  72 115 159 101  65  82  71 126  68 199  96  67 125
 249 105  92  78  77  79 223 242  70 102 109 107 119 194 113 106 247  80
  86  81  83 122 253 196 132 139  84 130  93 103 112 222 118  88 182 283
  90 128  89 235 190  76  87 133 153 129  98 148 123  91 211 131 108 187
 214 181 173 252  95 124 137 145 188 143 198 138 245 195 186 170 136 161
 157 141 205 271 192 142 140 134 240 185 244 210 184 202 296 213 273 219
 135 169 155 225 266 215 197 256 212 158 180 166 168 183 162 191 179 150
 146 276 165 239 237 193 229 274 207 295 208 172 217 206 201 171 152 156
 174 238 167 151 144 163 287 209 290 220 228 232 178 177 275 176 281 149
 298 255 216 285 226 160 147 254 164 175 297 234 284 204 218 261 231 248
 286 230 268 203]

Column: months_since_last_claim
Unique values (37): [ 7.          3.         34.         10.         15.14907074  2.
  8.         35.         33.         19.         13.          5.
 24.         25.          6.         20.         26.         14.
  9.         29.         11.          1.         18.         16.
 30.         12.          4.         22.         31.         21.
 28.         17.         15.         32.         23.         27.
  0.        ]

Column: months_since_policy_inception
Unique values (100): [52 26 31  3 73 99 45 24  8 29 32 25 28 87 10 74  1 38 58 37  7 80 95 78
 63 27 97 39 11 59 46 62 13 54 51 22 82 91 44 43 76 48 84  6 92 12 61  4
 18 66 70 16 75 34 35 64  9 89  0 60 71 23 55 93  2 67 81 40 57 86 19 72
 69 33 47 42 17 49 21 83 94 30 15 50 53 77 41 90  5 79 56 98 20 88 65 14
 85 96 36 68]

Column: number_of_open_complaints
Unique values (6): <IntegerArray>
[0, 3, 1, 2, 4, 5]
Length: 6, dtype: Int64

Column: number_of_policies
Unique values (9): [9 1 2 7 4 3 6 8 5]

Column: policy_type
Unique values (3): ['Corporate Auto' 'Personal Auto' 'Special Auto']

Column: policy
Unique values (9): ['Corporate L3' 'Personal L3' 'Personal L2' 'Corporate L2' 'Personal L1'
 'Special L1' 'Corporate L1' 'Special L3' 'Special L2']

Column: renew_offer_type
Unique values (4): ['Offer3' 'Offer4' 'Offer2' 'Offer1']

Column: sales_channel
Unique values (4): ['Agent' 'Call Center' 'Branch' 'Web']

Column: total_claim_amount
Unique values (5106): [292.8      744.924331 480.       ... 273.018929 381.306996 618.288849]

Column: vehicle_class
Unique values (4): ['Four-Door Car' 'SUV' 'Two-Door Car' 'Luxury']

Column: vehicle_size
Unique values (3): ['Medium' 'Small' 'Large']

Column: vehicle_type
Unique values (1): ['A']

Column: month
Unique values (2): ['Feb' 'Jan']


Data types check:
  ➡️customer_id               object     [9134] unique values
  ➡️state                     object     [5] unique values
  ➡️customer_lifetime_value   float64    [8041] unique values
  ➡️response                  object     [2] unique values
  ➡️coverage                  object     [3] unique values
  ➡️education                 object     [5] unique values
  ➡️effective_to_date         object     [59] unique values
  ➡️employment_status         object     [5] unique values
  ➡️gender                    object     [2] unique values
  ➡️income                    int64      [5694] unique values
  ➡️location_code             object     [3] unique values
  ➡️marital_status            object     [3] unique values
  ➡️monthly_premium_auto      int64      [202] unique values
  ➡️months_since_last_claim   float64    [37] unique values
  ➡️months_since_policy_inception int64      [100] unique values
  ➡️number_of_open_complaints Int64      [6] unique values
  ➡️number_of_policies        int64      [9] unique values
  ➡️policy_type               object     [3] unique values
  ➡️policy                    object     [9] unique values
  ➡️renew_offer_type          object     [4] unique values
  ➡️sales_channel             object     [4] unique values
  ➡️total_claim_amount        float64    [5106] unique values
  ➡️vehicle_class             object     [4] unique values
  ➡️vehicle_size              object     [3] unique values
  ➡️vehicle_type              object     [1] unique values
  ➡️month                     object     [2] unique values
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    10910 non-null  object
 1   state                          10910 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10910 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  object
 7   employment_status              10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10910 non-null  float64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10910 non-null  Int64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10910 non-null  object
 23  vehicle_size                   10910 non-null  object
 24  vehicle_type                   10910 non-null  object
 25  month                          10910 non-null  object
dtypes: Int64(1), float64(3), int64(4), object(18)
memory usage: 2.2+ MB

<hr>

## 3️⃣ DATA TYPES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [20]:
import pandas as pd

# Load the step 03 dataset into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_02_invalid-values.csv")

# check data types before data formatting
print("Data types before data formatting:")
df.info()

Data types before data formatting:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    10910 non-null  object
 1   state                          10910 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10910 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  object
 7   employment_status              10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10910 non-null  float64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10910 non-null  int64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10910 non-null  object
 23  vehicle_size                   10910 non-null  object
 24  vehicle_type                   10910 non-null  object
 25  month                          10910 non-null  object
dtypes: float64(3), int64(5), object(18)
memory usage: 2.2+ MB

In [21]:
# convert effective_to_date column to datetime format
print("Before: 'effective_to_date' data type:", df['effective_to_date'].dtype)
df['effective_to_date'] = pd.to_datetime(df['effective_to_date'], errors='coerce')
print("After: 'effective_to_date' data type:", df['effective_to_date'].dtype)
print("*" * 70)

# convert income to float
print("Before: 'income' data type:", df['income'].dtype)
df['income'] = pd.to_numeric(df['income'], errors='coerce').astype(float)
print("After: 'income' data type:", df['income'].dtype)
print("*" * 70)

# convert months_since_last_claim to integer and round to the nearest integer
print("Before: 'months_since_last_claim' data type:", df['months_since_last_claim'].dtype)
df['months_since_last_claim'] = pd.to_numeric(df['months_since_last_claim'], errors='coerce').round().astype('Int64')
print("After: 'months_since_last_claim' data type:", df['months_since_last_claim'].dtype)
print("*" * 70)

# check data types after data formatting
print("Data types after data formatting:")
df.info()
print("*" * 70)

# display the dataset after data formatting ----------------------------------------------------------------------
print("Dataset after data formatting:")
print("Dataset shape:", df.shape)
display(df.head())

# save step 3 data formatting dataset into a new CSV file ------------------------------
df.to_csv("marketing_customer_analysis_03_data-formatting.csv", index=False)

Before: 'effective_to_date' data type: object
After: 'effective_to_date' data type: datetime64[ns]
**********************************************************************
Before: 'income' data type: int64
After: 'income' data type: float64
**********************************************************************
Before: 'months_since_last_claim' data type: float64
After: 'months_since_last_claim' data type: Int64
**********************************************************************
Data types after data formatting:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    10910 non-null  object
 1   state                          10910 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10910 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  datetime64[ns]
 7   employment_status              10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  float64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10910 non-null  Int64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10910 non-null  int64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10910 non-null  object
 23  vehicle_size                   10910 non-null  object
 24  vehicle_type                   10910 non-null  object
 25  month                          10910 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(3), int64(4), object(17)
memory usage: 2.2+ MB
**********************************************************************
Dataset after data formatting:
Dataset shape: (10910, 26)

,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029.0,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medium,A,Feb
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0.0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medium,A,Jan
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139.0,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medium,A,Feb
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078.0,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medium,A,Jan
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675.0,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medium,A,Jan

<hr>

## 4️⃣ NULL VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [22]:
import pandas as pd
# read csv
df = pd.read_csv("marketing_customer_analysis_03_data-formatting.csv")

# Check for null values
null_counts = df.isnull().sum()
print(f"Total null count in the Dataframe = {null_counts.sum()}\n")

# Identify how many null values each column has. 
print("Columns with null values:")
display(null_counts[null_counts > 0])

print("-" * 70)

# show null values in each column
print("Null values in each column:")
# Loop through each column and print the number of nulls in each column
for col in df.columns:
    null_count = df[col].isnull().sum()
    print(f"Column '{col}'➡️[{null_count}] null values")

# save the dataset after checking for null values into a new CSV file
df.to_csv("marketing_customer_analysis_04_no-nulls.csv", index=False)

Total null count in the Dataframe = 0

Columns with null values:

Series([], dtype: int64)

----------------------------------------------------------------------
Null values in each column:
Column 'customer_id'➡️[0] null values
Column 'state'➡️[0] null values
Column 'customer_lifetime_value'➡️[0] null values
Column 'response'➡️[0] null values
Column 'coverage'➡️[0] null values
Column 'education'➡️[0] null values
Column 'effective_to_date'➡️[0] null values
Column 'employment_status'➡️[0] null values
Column 'gender'➡️[0] null values
Column 'income'➡️[0] null values
Column 'location_code'➡️[0] null values
Column 'marital_status'➡️[0] null values
Column 'monthly_premium_auto'➡️[0] null values
Column 'months_since_last_claim'➡️[0] null values
Column 'months_since_policy_inception'➡️[0] null values
Column 'number_of_open_complaints'➡️[0] null values
Column 'number_of_policies'➡️[0] null values
Column 'policy_type'➡️[0] null values
Column 'policy'➡️[0] null values
Column 'renew_offer_type'➡️[0] null values
Column 'sales_channel'➡️[0] null values
Column 'total_claim_amount'➡️[0] null values
Column 'vehicle_class'➡️[0] null values
Column 'vehicle_size'➡️[0] null values
Column 'vehicle_type'➡️[0] null values
Column 'month'➡️[0] null values

<hr>

## 5️⃣ DUPLICATE VALUES


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [23]:
import pandas as pd

# read csv into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_04_no-nulls.csv")

# Check for duplicate rows in the DataFrame
duplicate_rows = df[df.duplicated()]

# Shape of the dataset before dropping duplicate rows
print("Dataset shape before dropping duplicates:", df.shape)

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicate_rows.shape[0]}")

# Display the duplicate rows
if duplicate_rows.empty:
    print("No duplicate rows found.")
else:
    print("\nDuplicate rows:")
    display(duplicate_rows)

print(*70*"-")

# drop duplicate rows, keeping the first occurrence
print("Dropping duplicate rows, keeping the first occurrence...")
df.drop_duplicates(keep='first', inplace=True)
duplicate_rows = df[df.duplicated()]

# Display the duplicate rows
if duplicate_rows.empty:
    print("No duplicate rows found.")
else:
    print("\nDuplicate rows:")
    display(duplicate_rows)
    
# save the dataset after dropping duplicate rows into a new CSV file
df.to_csv("marketing_customer_analysis_05_no-duplicates.csv", index=False)
print(*70*"-")

Dataset shape before dropping duplicates: (10910, 26)
Number of duplicate rows: 460

Duplicate rows:

,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
644,SK12432,Arizona,2388.353882,No,Basic,Bachelor,2011-02-14,Unemployed,M,0.0,...,1,Personal Auto,Personal L1,Offer2,Web,677.970934,Four-Door Car,Medium,A,Feb
645,BZ85280,Oregon,7284.262288,No,Basic,College,2011-02-23,Medical Leave,M,10334.0,...,2,Personal Auto,Personal L1,Offer3,Agent,296.962938,Four-Door Car,Medium,A,Feb
707,KX23516,California,4455.843406,No,Extended,High School or Below,2011-02-20,Unemployed,F,0.0,...,1,Personal Auto,Personal L3,Offer4,Agent,699.615192,SUV,Medium,A,Feb
895,ON44465,California,5313.294035,No,Extended,High School or Below,2011-01-24,Unemployed,F,0.0,...,9,Personal Auto,Personal L2,Offer1,Agent,863.394700,Four-Door Car,Medium,A,Jan
901,YZ19736,Arizona,2580.849899,Yes,Basic,College,2011-02-09,Employed,M,46900.0,...,1,Personal Auto,Personal L2,Offer2,Web,316.800000,Four-Door Car,Medium,A,Feb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2011-02-07,Employed,F,57693.0,...,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medium,A,Feb
10886,OS84395,Nevada,7611.949286,No,Extended,Bachelor,2011-02-25,Employed,M,90252.0,...,7,Corporate Auto,Corporate L2,Offer2,Web,122.924197,Four-Door Car,Medium,A,Feb
10888,MN95006,California,6928.601611,No,Basic,Bachelor,2011-01-10,Employed,M,22907.0,...,1,Personal Auto,Personal L2,Offer4,Call Center,49.187760,Luxury,Medium,A,Jan
10894,EX63393,California,6314.492009,No,Extended,Master,2011-02-27,Employed,F,66947.0,...,6,Personal Auto,Personal L1,Offer3,Agent,374.400000,Four-Door Car,Small,A,Feb
10899,WU60905,California,8610.667489,No,Basic,High School or Below,2011-02-06,Unemployed,F,0.0,...,9,Corporate Auto,Corporate L1,Offer3,Web,532.800000,SUV,Medium,A,Feb

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dropping duplicate rows, keeping the first occurrence...
No duplicate rows found.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In [24]:
import pandas as pd
# read csv into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_05_no-duplicates.csv")

# display the dataset ----------------------------------------------------------------------
print("Clean Dataset:")
print("Clean Dataset shape:", df.shape)
display(df.head(20))

# save the clean dataset into a new CSV file
df.to_csv("marketing_customer_analysis_06_clean.csv", index=False)

Clean Dataset:
Clean Dataset shape: (10450, 26)

,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029.0,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medium,A,Feb
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0.0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medium,A,Jan
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139.0,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medium,A,Feb
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078.0,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medium,A,Jan
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675.0,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medium,A,Jan
5,HO81102,California,4745.181764,No,Basic,High School or Below,2011-02-14,Employed,M,50549.0,...,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medium,A,Feb
6,IW72280,California,5035.035257,No,Basic,Doctor,2011-02-14,Employed,F,37405.0,...,4,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medium,A,Feb
7,IH64929,California,4956.247235,No,Basic,High School or Below,2011-02-24,Employed,M,87197.0,...,3,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medium,A,Feb
8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,66839.0,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Luxury,Medium,A,Jan
9,QX31376,Oregon,17114.328150,No,Extended,Master,2011-01-04,Employed,F,70961.0,...,2,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,A,Jan
10,HG93801,Arizona,5154.764074,No,Extended,High School or Below,2011-01-02,Employed,M,82730.0,...,1,Corporate Auto,Corporate L3,Offer2,Branch,442.521087,SUV,Large,A,Jan
11,GE63585,California,2420.711888,No,Basic,Bachelor,2011-02-07,Employed,M,31710.0,...,1,Corporate Auto,Corporate L3,Offer1,Call Center,199.551735,Two-Door Car,Medium,A,Feb
12,EO51920,Oregon,19955.257130,No,Extended,High School or Below,2011-01-31,Employed,F,69096.0,...,2,Corporate Auto,Corporate L3,Offer1,Agent,64.669515,Four-Door Car,Medium,A,Jan
13,KR82385,California,5454.587929,No,Basic,Master,2011-01-26,Employed,M,66334.0,...,4,Personal Auto,Personal L3,Offer4,Call Center,331.200000,Two-Door Car,Medium,A,Jan
14,TL59568,Arizona,12836.009510,No,Premium,High School or Below,2011-02-28,Unemployed,M,0.0,...,2,Personal Auto,Personal L2,Offer3,Agent,835.200000,Two-Door Car,Medium,A,Feb
15,CW49887,California,4626.801093,Yes,Basic,Master,2011-01-16,Employed,F,79487.0,...,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medium,A,Jan
16,FH51383,California,5326.677654,No,Basic,High School or Below,2011-02-07,Employed,F,76717.0,...,6,Personal Auto,Personal L3,Offer4,Call Center,300.528579,Two-Door Car,Large,A,Feb
17,TR26615,Oregon,2497.531509,No,Basic,High School or Below,2011-01-17,Unemployed,M,0.0,...,1,Corporate Auto,Corporate L2,Offer2,Branch,272.381465,Two-Door Car,Medium,A,Jan
18,ZC97968,California,2736.352663,No,Basic,College,2011-02-14,Disabled,M,17533.0,...,1,Personal Auto,Personal L3,Offer1,Agent,350.400000,Two-Door Car,Medium,A,Feb
19,NJ54277,California,3746.751625,Yes,Extended,College,2011-02-26,Employed,F,41479.0,...,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A,Feb

<hr>

## 6️⃣ ANALYSIS


<style>
h1 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h2 {
    text-align: left;
    color: darkblue;
    font-weight: bold;
}
</style>

<style>
h3 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>

<style>
h4 {
    text-align: center;
    color: black;
    font-weight: bold;
}
</style>
<hr>

In [25]:
import pandas as pd

# load the clean dataset into a new DataFrame
df = pd.read_csv("marketing_customer_analysis_06_clean.csv")

# display the dataset
print("Exploring the Clean Marketing Customer Dataset:")

# Display df DataFrame SHAPE
print(f"Clean Dataset Shape: [{df.shape[0]}] ROWS and [{df.shape[1]}] COLUMNS\n")

# Display df DataFrame HEAD
display(df.head())

# Display data types & missing values of each column in df DataFrame
print("Data Types & Missing Values of Each Column:")
display(df.info())

Exploring the Clean Marketing Customer Dataset:
Clean Dataset Shape: [10450] ROWS and [26] COLUMNS

,customer_id,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029.0,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medium,A,Feb
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0.0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medium,A,Jan
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139.0,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medium,A,Feb
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078.0,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medium,A,Jan
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675.0,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medium,A,Jan

Data Types & Missing Values of Each Column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10450 entries, 0 to 10449
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    10450 non-null  object
 1   state                          10450 non-null  object
 2   customer_lifetime_value        10450 non-null  float64
 3   response                       10450 non-null  object
 4   coverage                       10450 non-null  object
 5   education                      10450 non-null  object
 6   effective_to_date              10450 non-null  object
 7   employment_status              10450 non-null  object
 8   gender                         10450 non-null  object
 9   income                         10450 non-null  float64
 10  location_code                  10450 non-null  object
 11  marital_status                 10450 non-null  object
 12  monthly_premium_auto           10450 non-null  int64
 13  months_since_last_claim        10450 non-null  int64
 14  months_since_policy_inception  10450 non-null  int64
 15  number_of_open_complaints      10450 non-null  int64
 16  number_of_policies             10450 non-null  int64
 17  policy_type                    10450 non-null  object
 18  policy                         10450 non-null  object
 19  renew_offer_type               10450 non-null  object
 20  sales_channel                  10450 non-null  object
 21  total_claim_amount             10450 non-null  float64
 22  vehicle_class                  10450 non-null  object
 23  vehicle_size                   10450 non-null  object
 24  vehicle_type                   10450 non-null  object
 25  month                          10450 non-null  object
dtypes: float64(3), int64(5), object(18)
memory usage: 2.1+ MB

None